name: postgresSemiRaw
services:
  # create container to run the postgresSemiRaw
  postgresSemiRaw:
    container_name: postgresSemiRaw
    image: postgressemiraw
    build:
      context: ../
      dockerfile: ./deploy/postgresRaw/Dockerfile
      args:
        JOBS: ${JOBS}
        BUILD_DATE: ${BUILD_DATE}
        VCS_REF: ${VCS_REF}
    env_file: .env
    ports:
      - "5554:5432"
    volumes:
      - ../data:/data
      - ../datasets:/datasets:ro
      - ../result:/result

  # create container to run the analysis
  analysis:
    container_name: analysis
    build:
      context: ../
      dockerfile: ./deploy/Analysis/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ../result:/result
    depends_on:
      - postgresSemiRaw