version: '3.8'

services:
  postgresRaw:
    container_name: postgresRaw
    image: semiraw/postgresraw
    build:
      context: ../
      dockerfile: ./deploy/postgresRaw/Dockerfile
      args:
        JOBS: 1
        BUILD_DATE: ${BUILD_DATE}
        VCS_REF: ${VCS_REF}
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db
    ports:
      - "5554:5432"
    volumes:
      - ../data:/data:rw
      - ../datasets:/datasets:ro
      - ../postgresRaw:/usr/local/apps/postgresRaw
  #######################################################################
  postgresRawUI:
    container_name: postgresRaw-ui
    image: semiraw/postgresraw-ui
    build:
      context: ../
      dockerfile: ./deploy/postgresRawUI/Dockerfile
      args:
        JOBS: 1
        BUILD_DATE: ${BUILD_DATE}
        VCS_REF: ${VCS_REF}
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db
    ports:
      - "4445:5555"
    volumes:
      - ../data:/data:rw
      - ../datasets:/datasets:ro
      - ../postgresRaw:/usr/local/apps/postgresRaw
    links:
      - postgresRaw:db
